package com.a5starcompany.topwisemp35p.emvreader.emv


data class CardReadResult(
    var issuerApplicationData: String = "",
    var applicationVersionNumber: String = "",
    var transactionType: String = "",
    var amount: String = "",
    var amountAuthorized: String = "",
    var cardSeqenceNumber: String = "",
    var unifiedPaymentIccData: String = "",
    var deviceSerialNumber: String = "",
    var iccDataString: String = "",
    var authorizationResponseCode: String = "",
    var nibssIccSubset: String = "",
    var applicationTransactionCounter: String = "",
    var terminalVerificationResults: String = "",
    var expirationDate: String = "",
    var applicationPrimaryAccountNumber: String = "",
    var applicationPANSequenceNumber: String = "",
    var transactionDate: String = "",
    var cryptogramInformationData: String = "",
    var dedicatedFileName: String = "",
    var applicationIssuerData: String = "",
    var transactionSequenceNumber: String = "",
    var transactionSequenceCounter: String = "",
    var cryptogram: String = "",
    var track2Data: String = "",
    var cardholderVerificationMethod: String = "",
    var applicationInterchangeProfile: String = "",
    var pinBlockDUKPT: String = "",
    var pinBlockTrippleDES: String = "",
    var pinBlock: String = "",
    var cardScheme: String = "",
    var applicationDiscretionaryData: String = "",
    var unpredictableNumber: String = "",
    var interfaceDeviceSerialNumber: String = "",
    var encryptedPinBlock: String = "",
    var terminalType: String = "",
    var cardHolderName: String = "",
    var originalDeviceSerial: String = "",
    var transactionCurrencyCode: String = "",
    var terminalCountryCode: String = "",
    var cashBackAmount: String = "",
    var terminalCapabilities: String = "",
    var plainPinKey: String = "",
    var originalPan: String = "",
    var accountType: String = "",
)